######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 3 14:31:57 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . c
INCLUDEPATH += .
LIBS = -lnetsnmpagent
QT += network
QT -= gui

# Input
HEADERS += QSnmp.hpp Door.hpp DoorServer.hpp
SOURCES += main.cpp QSnmp.cpp Door.cpp DoorServer.cpp
